name: Build Knote App image and publish to Docker Hub
env:
  DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_TOKEN}}
  DOCKER_REPOSITORY: image-app
  NODE_IMAGE_TAG: knote-app-v1.0.0

on:
  push:
    branches: [main]

permissions:
  actions: read
  security-events: write

jobs:
  build-knote-image:
    # if: github.ref == 'refs/heads/image-app-build' && github.event_name == 'push'
    name: Build-Scan-Publish Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    # Docker Setup QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

     # Build and tag Image 
    - name: Build and Tag Image
      # if: github.ref == 'refs/heads/image-app-build' && github.event_name == 'push'
      run: |
        docker build -t ${{env.DOCKER_USER}}/${{env.DOCKER_REPOSITORY}}:${{env.NODE_IMAGE_TAG}} ./knote
        
    - name: Run Trivy vulnerability scanner
      # if: github.ref == 'refs/heads/image-app-build' && github.event_name == 'push'
      id: scan
      uses: crazy-max/ghaction-container-scan@v3
      with: 
        image: ${{env.DOCKER_USER}}/${{env.DOCKER_REPOSITORY}}:${{env.NODE_IMAGE_TAG}}
        annotations: true
        dockerfile: ./Dockerfile
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Upload Scan Result SARIF file to GitHub Code Scanning
      # if: github.ref == 'refs/heads/image-app-build' && github.event_name == 'push'
      if: ${{ steps.scan.outputs.sarif != '' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
       
    - name: Push Image built to Docker Hub private repository
      # if: github.ref == 'refs/heads/image-app-build' && github.event_name == 'push'   
      run: |
        docker login -u ${{env.DOCKER_USER}} -p ${{env.DOCKER_PASSWORD}}
        docker push ${{env.DOCKER_USER}}/${{env.DOCKER_REPOSITORY}}:${{env.NODE_IMAGE_TAG}}
